#!/bin/bash
#: Title        : can
#: Date         : 2023-11-26
#: Author       : caizhifei2023@gmail.com
#: Description  : Script utilities for software installation or service configuration on ubuntu server

source "./vars"

echo "[Environment Variables]"
echo "Path: $PATH"
echo "Home: $HOME"
echo "Current Directory: $PWD"
echo "SOURCE_BASE: $SOURCE_BASE"
echo '$#: ' "$#"
echo '$0: ' "$0"
echo '$1: ' "$1"

# %s %c %d %f 都是格式替代符，％s 输出一个字符串，％d 整型输出，％c 输出一个字符，％f 输出实数，以小数形式输出。
# %-10s 指一个宽度为 10 个字符（- 表示左对齐，没有则表示右对齐），任何字符都会被显示在 10 个字符宽的字符内，如果不足则自动以空格填充，超过也会将内容全部显示出来。
# %-4.2f 指格式化为小数，其中 .2 指保留2位小数。
printf "%s %s %d\n" "Hello, World" "!" 123
